// Generated by CoffeeScript 2.3.2
// 99 Bottles on the wall
var i, s, s_;

i = 19;

while (i -= 1) {
  s = i === 1 ? "" : "s";
  s_ = i - 1 === 1 ? "" : "s";
  console.log(`${i} bottle${s} of beer on the wall, ${i} bottle${s} of beer!\n Take one down, pass it around, ${i - 1} bottle${s_} of bear on the wall!`);
}
