// Generated by CoffeeScript 2.3.2
// FizzBuzz.coffee
var fizzbuzz, j, num;

fizzbuzz = function(i) {
  var output;
  output = "";
  if (i % 3 === 0) {
    output += "fizz";
  }
  if (i % 5 === 0) {
    output += "buzz";
  }
  if (i % 3 !== 0 && i % 5 !== 0) {
    output = i;
  }
  return i + ": " + output;
};

for (num = j = 1; j <= 20; num = ++j) {
  console.log(fizzbuzz(num));
}
